[tool.ruff]
# Configuration for Ruff, Python Linter
line-length = 100
target-version = "py39"
exclude = [
    ".github",
    ".pytest_cache",
    "config",
    "doc",
    "docs",
    "dashboard/__pychache_",
    "docker-conf",
    "files",
    "logs",
    "templates",
    "venv",
    ".env",
    "processor/database/alembic"
]
select = ["E4", "E7", "E9", "F", "I"]